version: '3'
 
services:
  haproxy:
    image: haproxy:2.5.4-alpine
    ports:
      - "80:80/tcp"
      - "25565:25565/tcp"
    volumes:
      - ./haproxy.cfg.default:/usr/local/etc/haproxy/haproxy.cfg
