version: '3.3'
  
networks:
  haproxy-network:
    external: false

services:
  haproxy:
    build: .
    restart: always
    environment:
      - TZ=Asia/Tokyo
    networks:
      - haproxy-network
    ports:
      - "80:80/tcp"
      - "25565:25565/tcp"
    volumes:
      - ./haproxy.cfg.default:/usr/local/etc/haproxy/haproxy.cfg
